nodes: 1
tasks_per_node: 8
tag: default
eval_name: intphys2
folder: /checkpoint/vmaev2_g/
resume_checkpoint: false
experiment:
  data:
    batch_size: 1
    resolution: 224
    stride_sliding_window: 2
    use_bfloat16: true
    frames_per_clip: 16
    context_lengths: [4,6,8,10,12,14]
    frame_steps: 10
    num_frames_to_pred: -1
    dataset: intphys2-debug
  max_context_mode: true
model_kwargs:
  checkpoint: /checkpoint/vmaev2_g/vit_g_hybrid_pt_1200e.pth
  module_name: app.videomaev2.modelcustom.default_wrapper
  wrapper_kwargs:
    no_predictor: false
    # num_output_frames: 2
  pretrain_kwargs:
    resolution: 224
    encoder:
      model_name: pretrain_videomae_giant_patch14_224